### ISSUE TITLE
ModuleNotFoundError: No module named 'nuscenes'

### ISSUE THREAD

**Issue by 18780165950** [wzzheng/TPVFormer#72]
Traceback (most recent call last):
  File "train.py", line 332, in <module>
    torch.multiprocessing.spawn(main, args=(args,), nprocs=args.gpus)
  File "/home/zkxq/anaconda3/envs/occupancy/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/zkxq/anaconda3/envs/occupancy/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/zkxq/anaconda3/envs/occupancy/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/home/zkxq/anaconda3/envs/occupancy/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/netdrive/project/tangzihang/3D/occupancy/TPVFormer-main/TPVFormer-main/train.py", line 100, in main
    from builder import data_builder
  File "/netdrive/project/tangzihang/3D/occupancy/TPVFormer-main/TPVFormer-main/builder/data_builder.py", line 4, in <module>
    from nuscenes import NuScenes
ModuleNotFoundError: No module named 'nuscenes'

**Comment by zzwon1212** [comment]
`pip install nuscenes-devkit` may solve that error.

**Comment by 18780165950** [comment]
您好，您发的邮件我已收到，我尽快给您回复。
